### ISSUE TITLE
PHP 5.4.* syntax error, unexpected 'class' (T_CLASS)

### ISSUE THREAD

**Issue by williamyiu** [Insolita/yii2-migrik#13]
Error in Bootstrap.php, with IMigrationTableResolver::class
    public function bootstrap($app)
    {
        if ($app->hasModule('gii')) {
            if (!isset($app->getModule('gii')->generators['migrik'])) {
                $app->getModule('gii')->generators['migrik'] = 'insolita\migrik\gii\StructureGenerator';
                $app->getModule('gii')->generators['migrikdata'] = 'insolita\migrik\gii\DataGenerator';
                $app->getModule('gii')->generators['migrikdoc'] = 'insolita\migrik\gii\ByModelGenerator';
            }
            \Yii::$container->set(IMigrationTableResolver::class, TableResolver::class);
            \Yii::$container->set(IPhpdocResolver::class, PhpDocResolver::class);
            \Yii::$container->set(IModelResolver::class, ModelResolver::class);
        }
    }
}

::class is only supported PHP 5.5+. I am using PHP 5.4.*. What can I do to fix this?

**Comment by Insolita** [comment]
i replace ::class usage, but why you use so old php version? php5.5 was released more than three years ago!!!
