### ISSUE TITLE
From table migration ignores foreign key on delete Cascade

### ISSUE THREAD

**Issue by dhiraj** [Insolita/yii2-migrik#15]
The migration needs to add 'Cascade' in the relation generation.

**Comment by Insolita** [comment]
what kind of migrations? more info and examples please

**Comment by dhiraj** [comment]
Sure, I'm creating a "migration file for the specified database table", the first option. My idea is that I will manually create full table schema using GUI like MySQL workbench and then use migrik to generate a migration and switch over to using that.

So I made a user table and an uploads table. The uploads table has a column id_user that is a foreign key to user table's id primary key. I set the foriegn key to cascade delete and update.

When I run the migration, the table gets created as "RESTRICT", because no cascade is supplied in the migration for update and delete. I manually change the generated migration and add cascade in the statement, and then it works.

**BEFORE**

``` PHP
        $this->addForeignKey('fk_image_id','{{%image}}','id','user', 'id');
```

**AFTER**

``` PHP
        $this->addForeignKey('fk_image_id','{{%image}}','id','user', 'id','CASCADE','CASCADE');
```

**Comment by Insolita** [comment]
https://github.com/Insolita/yii2-migrik#use-own-templates this can be the decision
Copy folder vendor/insolita/yii2-migrik/gii/default_structure  into any place of your project (for ex. /common/gii/migrik_templates);
modify file relation.php 
- change this line https://github.com/Insolita/yii2-migrik/blob/master/gii/default_structure/relation.php#L31
  to

``` php
$this->addForeignKey('fk_<?=$table['tableName']?>_<?=$rel['pk']?>','<?=$table['tableAlias']?>','<?=$rel['pk']?>','<?=$rel['ftable']?>','<?=$rel['fk']?>', 'CASCADE', 'CASCADE');
```

and register path to you new template folder in config

``` php
$config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'allowedIPs' => ['127.0.0.1', 'localhost', '::1'],
        'generators' => [
            'migrik'=>[
                        'class'=>\insolita\migrik\gii\StructureGenerator::class,
                        'templates'=>
                        [
                             'custom'=>'@common/gii/migrik_templates/mycustom'
                        ]
            ],
        ]
]
```

and you be able to choose new template for generate relations with 'cascade' options without manual editiing. 

There are different cases and not only 'cascade' options may be used for foreign keys
