### ISSUE TITLE
Revert for table-data

### ISSUE THREAD

**Issue by myafk** [Insolita/yii2-migrik#20]
For SQL-DB thinks this code is best way to revert table-data migration:

>     public function safeDown()
>     {
> 	    $this->delete('{{%users}}');
> 	    $this->execute('ALTER TABLE {{%users}} AUTO_INCREMENT = 1;');
>     }

This code also remove / update all foreign keys and refresh autoincrement

**Comment by Insolita** [comment]
you can create any own templates for specific databases - it`s simple 
see section https://github.com/Insolita/yii2-migrik#customizing
And official gii documentation https://github.com/yiisoft/yii2-gii/blob/master/docs/guide/topics-creating-your-own-templates.md
