### ISSUE TITLE
Error DateTime

### ISSUE THREAD

**Issue by myafk** [Insolita/yii2-migrik#25]
http://prnt.sc/dxk7ld

I guess that the error due to the fact that function createFromFormat goes an int, but it takes only a string.
http://php.net/manual/ru/datetime.createfromformat.php

When i change:
`$uPrefix = (int)preg_replace('~[^0-9]~', '', $prefix);`
To:
`$uPrefix = preg_replace('~[^0-9]~', '', $prefix);`
Error has been fixed.

**Comment by Insolita** [comment]
#24
