### ISSUE TITLE
Bugs with new generator by phpdoc annotations; 

### ISSUE THREAD

**Issue by vincenzodiroberto** [Insolita/yii2-migrik#29]
Hello to all,
I'm having problems in the migration of models whose name ends with 't', 'x' or 'n'. In these cases, the name of the inserted pattern is cut and the class is not rightly identified
Am I doing something wrong?
Thanks a lot,
Vincenzo

![cattura](https://cloud.githubusercontent.com/assets/19969214/23309803/6af09044-fab0-11e6-8d85-c244f6cf8568.PNG)

**Comment by Insolita** [comment]
try
```
app\models\Test
```

FQN - full qualified namespace
