### ISSUE TITLE
When generating migration with a table column of type tinyint, it becomes $this->tinyint(), but it should be $this->tinyInteger()

### ISSUE THREAD

**Issue by william327** [Insolita/yii2-migrik#38]
When the table contains a column of type tinyint, the migration that is generated is
'foo'=> $this->tinyint(3) but should be 'foo'=> $this->tinyInteger(3)

I used the fluent interface and generation mode "One file per table". Version is 2.3

Reference: https://github.com/yiisoft/yii2/blob/master/framework/db/SchemaBuilderTrait.php#L100

**Comment by Insolita** [comment]
yes, it was added since 2.0.14
i will fix  soon
