### ISSUE TITLE
Composer can't find yii2-migrik

### ISSUE THREAD

**Issue by insane-tsunami** [Insolita/yii2-migrik#39]
Trying install via composer:

>  Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - The requested package insolita/yii2-migration-generator ~3.0 exists as insolita/yii2-migration-generator[1.0.0, 2.0, 2.1, 2.2, 2.2.1, 2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3, dev-dev2.3, dev-dev2.4, dev-master] but these are rejected by your constraint.

**Comment by Insolita** [comment]
fixed
