### ISSUE TITLE
Not Found (#404): Code file not found for mass migrates.

### ISSUE THREAD

**Issue by githubjeka** [Insolita/yii2-migrik#4]
![image](https://cloud.githubusercontent.com/assets/874234/5851920/72937442-a21f-11e4-96e4-fb9af6d1a3df.png)

**Comment by githubjeka** [comment]
![image](https://cloud.githubusercontent.com/assets/874234/5851979/572957de-a220-11e4-9f51-d74ea1517496.png)

**Comment by Insolita** [comment]
это условно  баг...это особенность превью gii просто файлы с таймстампом генерятся как в оригинальном создателе, чтоб очередность миграций сохранялась и превью фигово их цепляет

**Comment by githubjeka** [comment]
Но он не генерируется - файл не создаётся.

**Comment by githubjeka** [comment]
Разделение на модель, связь - два файла, работает успешно. Но всё в одном, так и не увидел как  работает.

**Comment by githubjeka** [comment]
Ok, thanks
