### ISSUE TITLE
Can you give me a case study?

### ISSUE THREAD

**Issue by changecj** [Insolita/yii2-migrik#45]
There are no examples to do the experiment

**Comment by Insolita** [comment]
? It's not clear for me, what kind of experiment, what case you want?

**Comment by changecj** [comment]
![image](https://user-images.githubusercontent.com/18041843/62779005-851b9d00-bae4-11e9-8d7b-d8d215f65600.png)

like using this pic to expalin a concept for newer

i am a new yii2 user and i try some minutes to understand how to use this extension !

if there is a pic like this ,i think i will understarnd it easily!

:)
