### ISSUE TITLE
Unknown Property – yii\base\UnknownPropertyException

### ISSUE THREAD

**Issue by den11100** [Insolita/yii2-migrik#47]
If write some name (example db2) in field "Database Connection ID"

and not have this Connection ID;

we get this error

Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: yii\web\Application::db2

And next time when you use migrik you have this error.

And fix only write next code.

$generator->db = 'db'  in file   /vendor/yiisoft/yii2-gii/src/views/default/view.php

Если прописать несуществующий connect
Database Connection ID
например db2

Получаем ошибку которую никак не убрать. 
Пока в файле  /vendor/yiisoft/yii2-gii/src/views/default/view.php   не пропишешь правильный коннект 
$generator->db = 'db' ;

После этого ошибка пропадает и костыль ($generator->db = 'db' ;) - можно убрать

**Comment by Insolita** [comment]
А зачем вы прописываете не существующий connect?

**Comment by Insolita** [comment]
'src/views/default/view.php'  - это что? вы пытаетесь свой шаблон для генерации сделать?

**Comment by den11100** [comment]
Если по ошибке указать неправильный коннект.   и закрыть потом браузер не нажимая назад. То будут траблы. которые решаются только , как я выше описал.

**Comment by den11100** [comment]
не кретично , просто если вдруг кто столкнётся, что бы знали как решить.

**Comment by den11100** [comment]
> 'src/views/default/view.php' - это что? вы пытаетесь свой шаблон для генерации сделать?

/vendor/yiisoft/yii2-gii/src/views/default/view.php

**Comment by den11100** [comment]
> А зачем вы прописываете не существующий connect?

Если по ошибке указать неправильный коннект. и закрыть потом браузер не нажимая назад. То будут траблы. которые решаются только , как я выше описал.

**Comment by den11100** [comment]
не кретично , просто если вдруг кто столкнётся, что бы знали как решить.
