### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by githubjeka** [Insolita/yii2-migrik#5]
This [line](https://github.com/Insolita/yii2-migrik/blob/5631a486f2cda449c757e38d2a24c159b1011cfd/gii/Generator.php#L232) should be attached to TYPE COLUMN

And why is `&& !$col->autoIncrement` ? 

I have 

``` sql
CREATE TABLE tablename (
 id int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
```

**Comment by Insolita** [comment]
Can you describe more? What you expect ?  May be pull request?

**Comment by githubjeka** [comment]
See https://dev.mysql.com/doc/refman/5.6/en/create-table.html 

create_definition: <<< column_definition: <<< data_type:

data_type has UNSIGNED , and not  column_definition

**Comment by githubjeka** [comment]
PR tomorrow, may be. 
:house:  :runner:

**Comment by githubjeka** [comment]
Everything remains the same for `TYPE_PK`. I changed my mind :shower:

**Comment by Insolita** [comment]
ok, thanks
