### ISSUE TITLE
generate data

### ISSUE THREAD

**Issue by cornernote** [Insolita/yii2-migrik#9]
Is there any plans to extend this with an option to also include the data?

**Comment by cornernote** [comment]
It's done in this other one I found, but I prefer your version because it's built with Gii rather than a stand-alone thing:

https://github.com/tmukherjee13/yii2-reverse-migration

**Comment by Insolita** [comment]
I am not sure that i need it; What is your purpose of using the table-based data migrations? I think for load initial data (like city\street db) is enough create pure sql dump from database (with phpmyadmin, or adminer (my preferenced https://www.adminer.org/ https://github.com/QuantumObject/docker-adminer https://github.com/InterativaDigital/yii2-adminer-module) ), store it in any project folder (for example @app/data or @app/common ) and write super-simple migration
`php

```
use yii\db\Migration;

class m160601_030527_menu extends Migration
{
     public function up()
     {
           $this->db->createCommand('SET FOREIGN_KEY_CHECKS=0;')->execute(); //disable check constrains for mysql
           $sql = file_get_contents(\Yii::getAlias('@app/data/myinitaldump.sql'));
           $this->db->createCommand($sql)->execute();
           $this->db->createCommand('SET FOREIGN_KEY_CHECKS=1;')->execute();
 }

public function down()
{
      // drop  or truncate needed tables
}
```

}
` 
In complex cases, still have to write by hands, often with models
For testing purpose i make https://github.com/Insolita/yii2-fixturegii that can generate fixture-arrays from table data, if fake data unsuitable

**Comment by cornernote** [comment]
Sometimes you want to include data as part of a module, it's cleaner and
database independent if it's in a migration. Otherwise why not just create
the tables the same way yeu described?

On 12 Aug 2016 10:45 pm, "Insolita" notifications@github.com wrote:

Im not sure that i need it; What is your purpose of using the table-based
data migrations? I think for load initial data is enough create pure sql
dump from database (with phpmyadmin, or adminer (my preferenced
https://www.adminer.org/ https://github.com/QuantumObject/docker-adminer
https://github.com/InterativaDigital/yii2-adminer-module) ), store it in
any project folder (for example @app/data or @app/common ) and write
super-simple migration
php
<?php

use yii\db\Migration;

class m160601_030527_menu extends Migration
{
public function up()
{
$this->db->createCommand('SET FOREIGN_KEY_CHECKS=0;')->execute(); //disable
check constrains for mysql
$sql = file_get_contents(\Yii::getAlias('@app/data/myinitaldump.sql'));
$this->db->createCommand($sql)->execute();
$this->db->createCommand('SET FOREIGN_KEY_CHECKS=1;')->execute();
}

public function down()
{
      // drop  or truncate needed tables
}

}
`
In complex cases, still have to write by hands
For testing purpose i make https://github.com/Insolita/yii2-fixturegii that
can generate fixture-arrays from table data, if fake data unsuitable

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/Insolita/yii2-migrik/issues/9#issuecomment-239442622,
or mute the thread

**Comment by Insolita** [comment]
> Otherwise why not just create the tables the same way yeu described?  

because table structure - depends from database, but basic insert query similar in all sql database 
So, i think about this after weekend;  Friday.. laziness. 
You can write wishes and suggestions

**Comment by cornernote** [comment]
That's a good point.  There are small differences, for example if I get a dump from phpmyadmin it will have backticks around the table and field names, which other databases won't support.  I believe there would be other small differences such as this.

If you are time short I will do a PR some time next week.  The basic concepts are already coded in the other module I linked to, however I will link to more specific parts of the code:

Get the data:
https://github.com/tmukherjee13/yii2-reverse-migration/blob/master/console/controllers/MigrationController.php#L300

Templates:
https://github.com/tmukherjee13/yii2-reverse-migration/blob/master/views/dataTemplate.php
https://github.com/tmukherjee13/yii2-reverse-migration/blob/master/views/_insertTable.php
https://github.com/tmukherjee13/yii2-reverse-migration/blob/master/views/_truncateTable.php

**Comment by Insolita** [comment]
So the wheather is not happy today;
See new release;
I hope that you will be satisfied

**Comment by cornernote** [comment]
Very cool, I'll give it a test when I get home in 2 hours. 

I had another suggestion that will make it more compatible with other database types, will open a new issue describing it in more detail
